apiVersion: v1
kind: Service
metadata:
  name: back-end-service
  labels:
    app: back-end
spec:
  type: NodePort
  selector:
    app: back-end
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      nodePort: 30085

