apiVersion: v1
kind: Service
metadata:
  name: back-end1-service
  labels:
    app: back-end1
spec:
  type: NodePort
  selector:
    app: back-end1
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      nodePort: 30082
